name: Kernel Build (A10 - Hybrid GCC)

on:
  workflow_dispatch:
    inputs:
      kernel_name:
        description: "Kernel Name"
        required: true
        default: "MIUI-A10"
      defconfig:
        description: "Defconfig"
        required: true
        default: "surya_defconfig"

env:
  KERNEL_NAME: ${{ github.event.inputs.kernel_name }}
  DEFCONFIG: ${{ github.event.inputs.defconfig }}
  BUILD_USER: fannndi
  BUILD_HOST: github

jobs:
  build:
    name: Compile Kernel (Hybrid)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Kernel Source
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          chmod +x deps.sh
          ./deps.sh

      - name: Create Swap (3G)
        run: |
          sudo fallocate -l 3G /swapfile
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile

      - name: Run build.sh
        run: |
          chmod +x build.sh
          ./build.sh

      - name: Upload Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: kernel-build-${{ github.run_id }}
          path: |
            build-artifacts/log.txt
            build-artifacts/${{ env.DEFCONFIG }}.snapshot
            out/.config
            out/dtb.img
            out/dtbo.img
            *.zip
          if-no-files-found: warn

      - name: Disable Swap
        if: always()
        run: sudo swapoff /swapfile
